# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Discount Mattress Shopify app config.
client_id = "14d24a16586b68797e8df536ff9852e9"
application_url = "https://ai-shop-assist-discount-mattress.vercel.app"
embedded = true
name = "Shop Assist"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://ai-shop-assist-discount-mattress.vercel.app/api/shopify/webhooks/compliance"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://ai-shop-assist-discount-mattress.vercel.app/api/shopify/webhooks/app-uninstalled"

[auth]
redirect_urls = [ "https://ai-shop-assist-discount-mattress.vercel.app/api/shopify/callback" ]

[build]
automatically_update_urls_on_dev = true
