# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# Main / future public Shopify app config.
client_id = "490e0122985fe1b9a296741745025ff2"
application_url = "https://rtg-roomie-chatbot-jy3i.vercel.app"
embedded = true
name = "Shop Assist"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://rtg-roomie-chatbot-jy3i.vercel.app/api/shopify/callback" ]

[build]
automatically_update_urls_on_dev = true
