/* eslint-disable @typescript-eslint/no-require-imports */
/**
 * Prebuild: converts Excel catalog, SYSTEM_PROMPT.md, and skills/*.md into
 * importable data files under src/data/.
 *
 * Catalog output is written to catalog-db.ts for the SQL retrieval planner.
 * Production multi-tenant runtime imports tenant-owned catalogs via the admin/API flow.
 */
const { readFileSync, writeFileSync, mkdirSync, readdirSync } = require("fs");
const { join, basename } = require("path");

console.log("[prebuild] cwd:", process.cwd());
console.log("[prebuild] node:", process.version);
console.log("[prebuild] files in cwd:", readdirSync(".").filter((f) => /\.(xlsx|md|json)$/.test(f)).join(", "));

let XLSX;
let initSqlJs;
try {
  XLSX = require("xlsx");
  initSqlJs = require("sql.js/dist/sql-asm.js");
  console.log("[prebuild] xlsx + sql.js loaded OK");
} catch (e) {
  console.error("[prebuild] FATAL: cannot load dependency:", e.message);
  process.exit(1);
}

const INDEXED_COLUMNS = [
  "category",
  "sale_price",
  "discount",
  "specialty_brand",
  "mattress_size",
  "mattress_type",
  "support_level",
  "temperature_management",
  "comfort",
];

function toSnakeCase(value) {
  return String(value || "")
    .trim()
    .replace(/[%]/g, " percent ")
    .replace(/[^\w]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_+/g, "_")
    .toLowerCase();
}

function escapeSqlIdentifier(value) {
  return `"${String(value).replace(/"/g, "\"\"")}"`;
}

function inferColumnType(column) {
  if (["count_of_reviews"].includes(column)) return "INTEGER";
  if (["avg_star_rating", "sale_price", "regular_price", "discount_percent"].includes(column)) return "REAL";
  return "TEXT";
}

function normalizeCell(value, type) {
  const text = String(value ?? "").trim();
  if (!text) return null;

  if (type === "INTEGER") {
    const parsed = Number.parseInt(text, 10);
    return Number.isFinite(parsed) ? parsed : null;
  }

  if (type === "REAL") {
    const parsed = Number.parseFloat(text.replace(/[^0-9.-]/g, ""));
    return Number.isFinite(parsed) ? parsed : null;
  }

  return text;
}

async function main() {
  const OUT = "src/data";
  mkdirSync(OUT, { recursive: true });

  const preferredExcel = readdirSync(".").find((f) => /^updated\s*rtg\.xlsx$/i.test(f));
  const excelFile = preferredExcel || readdirSync(".").find((f) => /\.xlsx$/i.test(f));

  if (excelFile) {
    console.log("[prebuild] Excel file found:", excelFile, "size:", readFileSync(excelFile).length, "bytes");

    const wb = XLSX.read(readFileSync(excelFile), { type: "buffer" });
    const targetSheet = wb.Sheets["Upload sheet"] || wb.Sheets[wb.SheetNames[0]];
    const rows = XLSX.utils.sheet_to_json(targetSheet, {
      defval: "",
      raw: false,
    });

    const headers = Object.keys(rows[0] || {});
    const seen = new Map();
    const columnMap = {};
    const columns = [];
    for (const header of headers) {
      const base = toSnakeCase(header);
      const count = seen.get(base) || 0;
      seen.set(base, count + 1);
      const column = count === 0 ? base : `${base}_${count + 1}`;
      columnMap[column] = header;
      columns.push({
        column,
        header,
        type: inferColumnType(column),
      });
    }

    const SQL = await initSqlJs();
    const db = new SQL.Database();
    db.run(
      `CREATE TABLE catalog_products (${columns
        .map(({ column, type }) => `${escapeSqlIdentifier(column)} ${type}`)
        .join(", ")});`
    );

    const insertSql = `INSERT INTO catalog_products (${columns
      .map(({ column }) => escapeSqlIdentifier(column))
      .join(", ")}) VALUES (${columns.map(() => "?").join(", ")});`;
    const stmt = db.prepare(insertSql);
    for (const row of rows) {
      stmt.run(columns.map(({ header, type }) => normalizeCell(row[header], type)));
    }
    stmt.free();

    for (const column of INDEXED_COLUMNS) {
      db.run(
        `CREATE INDEX IF NOT EXISTS ${escapeSqlIdentifier(`idx_catalog_products_${column}`)} ON catalog_products (${escapeSqlIdentifier(column)});`
      );
    }

    const dbBytes = db.export();
    db.close();

    const dbBase64 = Buffer.from(dbBytes).toString("base64");
    writeFileSync(
      join(OUT, "catalog-db.ts"),
      `// AUTO-GENERATED by scripts/prebuild.js — do not edit
export const CATALOG_DB_BASE64 = ${JSON.stringify(dbBase64)};
export const CATALOG_TABLE = "catalog_products";
export const CATALOG_COLUMN_TO_HEADER: Record<string, string> = ${JSON.stringify(columnMap, null, 2)};
export const CATALOG_HEADERS: string[] = ${JSON.stringify(headers)};
export const CATALOG_COLUMNS: string[] = ${JSON.stringify(columns.map(({ column }) => column))};
export const CATALOG_INDEXED_COLUMNS: string[] = ${JSON.stringify(INDEXED_COLUMNS)};
`
    );
    console.log(`✓ catalog-db.ts — ${rows.length} rows, ${columns.length} cols, ${dbBase64.length} base64 chars`);
  } else if (!readdirSync(OUT).includes("catalog-db.ts")) {
    console.error("[prebuild] FATAL: no Excel file found and no existing src/data/catalog-db.ts fallback is available.");
    process.exit(1);
  } else {
    console.log("[prebuild] No Excel file found — reusing existing src/data/catalog-db.ts fallback.");
  }

  const systemPrompt = readFileSync("SYSTEM_PROMPT.md", "utf-8");
  writeFileSync(
    join(OUT, "system-prompt-raw.ts"),
    `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const SYSTEM_PROMPT_RAW = ${JSON.stringify(systemPrompt)};\n`
  );
  console.log(`✓ system-prompt-raw.ts — ${systemPrompt.length} chars`);

  const skillsRoot = "skills";
  const skills = {};
  const registry = [];

  function parseFrontmatter(content) {
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match?.[1]) return {};
    const result = {};
    for (const line of match[1].split("\n")) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      const colonIndex = trimmed.indexOf(":");
      if (colonIndex <= 0) continue;
      const key = trimmed.slice(0, colonIndex).trim();
      let value = trimmed.slice(colonIndex + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      result[key] = value;
    }
    return result;
  }

  for (const entry of readdirSync(skillsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillFile = join(skillsRoot, entry.name, "SKILL.md");
    try {
      const content = readFileSync(skillFile, "utf-8");
      const frontmatter = parseFrontmatter(content);
      const name = frontmatter.name || entry.name;
      skills[name] = content;
      registry.push({
        name,
        description: frontmatter.description || `Skill ${name}`,
      });
    } catch {
      console.warn(`[prebuild] skipping invalid skill: ${entry.name}`);
    }
  }

  registry.sort((left, right) => left.name.localeCompare(right.name));

  writeFileSync(
    join(OUT, "skills-raw.ts"),
    `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const SKILLS_RAW: Record<string, string> = ${JSON.stringify(skills)};\n`
  );
  writeFileSync(
    join(OUT, "skills-registry.ts"),
    `// AUTO-GENERATED by scripts/prebuild.js — do not edit\nexport const SKILLS_REGISTRY: Array<{ name: string; description: string }> = ${JSON.stringify(registry, null, 2)};\n`
  );
  console.log(
    `✓ skills-raw.ts + skills-registry.ts — ${registry.length} skills: ${registry.map((skill) => skill.name).join(", ")}`
  );

  console.log("\nPrebuild complete.");
}

main().catch((error) => {
  console.error("[prebuild] FATAL:", error);
  process.exit(1);
});
