name: Sync Upstream Branches

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sync main
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: Pavanzapsight/rtg-roomie-chatbot
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

  sync-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sync prod
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: Pavanzapsight/rtg-roomie-chatbot
          upstream_sync_branch: prod
          target_sync_branch: prod
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
